### ISSUE TITLE
Example task fails

### ISSUE THREAD

**Issue by briceburg** [geekcell/github-action-aws-ecs-run-task#9]
The current full example task fails as `/bin/sh -c` only accepts a single argument. 

The [current example ](https://github.com/geekcell/github-action-aws-ecs-run-task/blob/444d28ae3d7c727cb0b881f4ed16d303abe29dea/README.md?plain=1#L38-L43)
```yml
override-container-command: |
  /bin/sh
  -c
  php artisan migrate --force --ansi && \
  php artisan db:seed --force --ansi && \
  php artisan config:clear --ansi
```

will produce an ecs `run-task` equivalent of:

```sh
 aws ecs run-task ... \
  --overrides '{ "containerOverrides": [ { "name": "foo", "command": ["/bin/sh", "-c", "php artisan migrate --force --ansi && \\", "php artisan db:seed --force --ansi && \\", "php artisan config:clear --ansi"] } ] }'
```

which executes the first argument (artisan migrate), but produces line 0 errors on the other commands. 

It would be great to support a shell command helper that merges the [multiline] commands into a single argument (when they trail with a `\`?). For now, I think we must do everything on a single line, e.g.

```yml
override-container-command: |
  /bin/sh
  -c
  php artisan migrate --force --ansi && php artisan db:seed --force --ansi && php artisan config:clear --ansi
```

and should update the example?

**Comment by Ic3w0lf** [comment]
Hi @briceburg 

I also stumbled upon this problem in the past and you are right about this issue, it's really dirty chaining multiple commands in a single line. 

I personally worked around this problem by having the `/bin/sh -c` as my container entryPoint instead of passing it via container command overrides. That way you should be able to just use a different YAML block style indicator and have all the lines concatenated into a single line, i.e:

```yaml
override-container-command: >-
  php artisan migrate --force --ansi &&
  php artisan db:seed --force --ansi &&
  php artisan config:clear --ansi
```

Sadly this forces you to create a new taskDefinition because AFAIK the `entryPoint` can't be overridden as of now. I was hoping AWS would provide the option to override this property soon so I can stop using this workaround, but no luck so far.

A shell command helper might a good idea but can also cause some confusion/conflict with the existing YAML block type rules. I might get back to this once I have some time. Thanks a lot for your suggestions!

**Comment by briceburg** [comment]
absolutely love this =) 

the writeup in https://github.com/geekcell/github-action-aws-ecs-run-task#appending-multiple-lines-into-a-single-command is excellent.
